"""Workstream G artifact emitter and accept-flow tests."""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from typer.testing import CliRunner

from neurobase.cli import app
from neurobase.core import projects
from neurobase.recommender import emitters, proposals
from neurobase.recommender.corpus import EvidenceRef
from neurobase.recommender.ranker import RankedCandidate, Scores

runner = CliRunner()


def _candidate(
    *, slug: str = "durable-rule", kind: str = "rule", target: str = "AGENTS.md"
) -> RankedCandidate:
    return RankedCandidate(
        slug,
        kind,
        "repeated-instruction",
        "Durable rule",
        "Repeated",
        "# Durable\n\nKeep this.",
        target,
        "proj",
        [],
        [EvidenceRef.proposal("old")],
        Scores(3, 2, 1.0, 6.0),
        2,
        1,
        1,
    )


def _setup(tmp_path: Path, candidate: RankedCandidate) -> tuple[Path, Path]:
    root, repo = tmp_path / "store", tmp_path / "repo"
    repo.mkdir()
    projects.register_project(root, repo, slug="proj")
    proposals.write_ranked(root, [candidate])
    return root, repo


def test_rule_preserves_unrelated_content_and_is_idempotent(tmp_path: Path) -> None:
    root, repo = _setup(tmp_path, _candidate())
    path = repo / "AGENTS.md"
    original = "before  \n"
    path.write_text(original, encoding="utf-8")
    doc = proposals.load_proposal(root, "durable-rule")
    assert doc is not None
    first = emitters.prepare(root, doc)
    emitters.write_atomic(first)
    assert first.path.read_text(encoding="utf-8").startswith(original)
    second = emitters.prepare(root, doc)
    assert second.before == second.after


def test_rule_damaged_markers_fail_closed(tmp_path: Path) -> None:
    root, repo = _setup(tmp_path, _candidate())
    path = repo / "AGENTS.md"
    path.write_text(
        "<!-- neurobase:rule:durable-rule (generated by `neurobase recommend accept` — "
        "hand edits inside this block are overwritten on the next accept of this proposal) -->\n",
        encoding="utf-8",
    )
    doc = proposals.load_proposal(root, "durable-rule")
    assert doc is not None
    with pytest.raises(ValueError, match="malformed"):
        emitters.prepare(root, doc)


def test_accept_diff_backup_consent_and_ledger(tmp_path: Path) -> None:
    root, repo = _setup(tmp_path, _candidate())
    path = repo / "AGENTS.md"
    path.write_text("foreign prose\n", encoding="utf-8")

    declined = runner.invoke(
        app, ["recommend", "accept", "durable-rule", "--root", str(root)], input="n\n"
    )
    assert declined.exit_code == 0
    assert path.read_text(encoding="utf-8") == "foreign prose\n"

    accepted = runner.invoke(
        app, ["recommend", "accept", "durable-rule", "--root", str(root), "--yes"]
    )
    assert accepted.exit_code == 0
    assert "foreign prose" in path.read_text(encoding="utf-8")
    manifests = list((root / "backups").glob("*/manifest.json"))
    assert len(manifests) == 1
    assert json.loads(manifests[0].read_text())[0]["original_abs_path"] == str(path.resolve())
    doc = proposals.load_proposal(root, "durable-rule")
    assert doc is not None and doc.get("status") == "accepted"
    assert proposals.ledger_history(root, "durable-rule")[-1]["event"] == "accepted"


def test_skill_foreign_ownership_and_redaction(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    home = tmp_path / "home"
    home.mkdir()
    monkeypatch.setenv("HOME", str(home))
    candidate = _candidate(kind="skill", target="user-skill")
    candidate = RankedCandidate(
        **{**candidate.__dict__, "draft": "# Skill\n\nAKIAIOSFODNN7EXAMPLE"}
    )
    root, _repo = _setup(tmp_path, candidate)
    doc = proposals.load_proposal(root, "durable-rule")
    assert doc is not None
    artifact = emitters.prepare(root, doc, skill_scope="user")
    artifact.path.parent.mkdir(parents=True)
    artifact.path.write_text("foreign", encoding="utf-8")
    artifact = emitters.prepare(root, doc, skill_scope="user")
    assert artifact.foreign is True
    assert "AKIAIOSFODNN7EXAMPLE" not in artifact.after
    assert "neurobase_managed: true" in artifact.after
