"""Consent-neutral artifact rendering for Phase 8 Workstream G."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from neurobase.core import redact, store
from neurobase.core.config import load_config
from neurobase.core.store_handle import StoreMode, open_store
from neurobase.recommender import proposals


@dataclass(frozen=True)
class Artifact:
    path: Path
    before: str
    after: str
    target: str
    foreign: bool = False


def _read_preserving(path: Path) -> str:
    """Read a target file with newline translation **disabled** so CRLF/mixed
    line endings survive verbatim — §12's "preserve every other byte" MUST.
    ``Path.read_text``'s universal-newline mode would silently rewrite ``\\r\\n``
    to ``\\n`` across the whole file on the next write. Returns ``""`` if absent."""
    if not path.exists():
        return ""
    with open(path, encoding="utf-8", newline="") as handle:
        return handle.read()


def read_target_text(path: Path) -> str:
    """Public read of an artifact target's current bytes, newline-preserving —
    the exact text `prepare`'s `Artifact.before` is built from. Callers that need
    to re-read a target at a mutation boundary (install's stale-preview guard) or
    inspect it for liveness use this so they see the file the same way the
    renderer does."""
    return _read_preserving(path)


def _rule_start_marker(slug: str) -> str:
    """The opening marker that identifies a slug's Neurobase-managed rule block
    inside an AGENTS.md/CLAUDE.md. Its presence is the liveness signal for a rule
    artifact: an accepted rule is live iff this marker is still in the target,
    independent of any foreign bytes the user added around it (ADR-0020 D39)."""
    return (
        f"<!-- neurobase:rule:{slug} (generated by `neurobase recommend accept` — "
        "hand edits inside this block are overwritten on the next accept of this proposal) -->"
    )


def prepare(root: Path, doc: store.Document, *, skill_scope: str | None = None) -> Artifact:
    draft = proposals.extract_draft(doc.body)
    if draft is None:
        raise ValueError("proposal has no valid managed draft region")
    # §12.8 belt-and-suspenders on the durable, often git-committed write
    # surface — redact with the SAME configured extras every other persist path
    # uses, not just the built-in table, so a custom pattern added after the
    # proposal was written still can't leak into the installed artifact.
    draft = redact.redact(draft, load_config().redact.extra_patterns)
    slug = str(doc.get("name") or "")
    kind = str(doc.get("type") or "")
    if kind == "skill":
        scope = skill_scope or ("user" if doc.get("target") == "user-skill" else "project")
        return _skill(root, doc, slug, draft, scope)
    if kind == "rule":
        return _rule(root, doc, slug, draft)
    raise ValueError(f"unsupported proposal type {kind!r}")


def _project_root(root: Path, doc: store.Document) -> Path:
    project = doc.get("project")
    if not isinstance(project, str) or not project:
        raise ValueError("this proposal has no single source project")
    roots = open_store(root, StoreMode.READ).load_registry().get(project)
    if not roots:
        raise ValueError(f"proposal project {project!r} is not registered")
    return Path(roots[0])


def _split_leading_frontmatter(text: str) -> tuple[dict[str, Any] | None, str]:
    """Split a leading ``---`` YAML frontmatter block off ``text``.

    Detection is *structural* and separate from YAML validity (F3): a leading block
    is present when ``text`` opens with ``---\\n`` and the first following ``---``
    is a clean fence line — its own line, closed by a newline or end-of-text.
    (Bodies here are the store's LF-normalised text, so ``\\r\\n`` never reaches
    this.) When no such block is present, returns ``(None, text)`` — all body.

    When a leading block *is* present it must parse to a YAML **mapping** to count
    as frontmatter; then its mapping and the body after it (leading blank lines
    trimmed) are returned, letting ``_skill`` drop a draft's *own* frontmatter so
    the installed SKILL.md carries exactly one (our) block. A leading block whose
    content is invalid YAML, or valid-but-not-a-mapping (a scalar/list — e.g. an
    ordinary Markdown ``---`` rule around prose), is **rejected with ValueError**:
    we neither embed it verbatim under our generated block (that reproduces the G3
    doubling) nor silently drop it (that would delete real body text). A draft must
    not carry its own frontmatter; a malformed leading fence is surfaced, not
    guessed — the accept flow turns this into a clear, named error."""
    if not text.startswith("---\n"):
        return None, text
    rest = text[4:]
    idx = rest.find("\n---")
    if idx < 0:
        return None, text  # a lone leading `---` with no closing fence — all body
    after_fence = rest[idx + 4 :]
    if after_fence and not after_fence.startswith("\n"):
        return None, text  # `\n---xyz` is not a fence line — not frontmatter
    frontmatter_text = rest[:idx]
    body = after_fence.lstrip("\n")
    try:
        parsed = yaml.safe_load(frontmatter_text)
    except yaml.YAMLError as exc:
        raise ValueError(f"draft's leading '---' block is not valid YAML: {exc}") from exc
    if not isinstance(parsed, dict):
        raise ValueError(
            "draft's leading '---' block is not a YAML mapping "
            "(a draft must not carry its own frontmatter)"
        )
    return parsed, body


def _skill_scope(doc: store.Document, override: str | None = None) -> str:
    """Resolve a skill proposal's scope. For an already-accepted proposal
    ``target`` records the scope actually used (D14), so it is authoritative when
    no explicit ``override`` is given — which is what lets a post-accept liveness
    check resolve the same SKILL.md path accept wrote to."""
    return override or ("user" if doc.get("target") == "user-skill" else "project")


def _skill_path(root: Path, doc: store.Document, slug: str, scope: str) -> Path:
    if scope not in {"user", "project"}:
        raise ValueError("skill target must be user or project")
    base = Path.home() if scope == "user" else _project_root(root, doc)
    return base / ".claude" / "skills" / slug / "SKILL.md"


def _rule_path(root: Path, doc: store.Document) -> Path:
    target = str(doc.get("target") or "")
    if target not in {"AGENTS.md", "CLAUDE.md"}:
        raise ValueError(f"invalid rule target {target!r}")
    return _project_root(root, doc) / target


def _project_roots(root: Path, doc: store.Document) -> list[Path]:
    """**Every** registered root for the proposal's project, not just the first.
    `_project_root` (singular) picks `roots[0]` for *rendering*, which is where a
    fresh accept writes; a liveness check must not inherit that narrowing —
    re-registering a moved repo under the same slug leaves `[old, new]`, and
    concluding "gone" from the stale `roots[0]` alone would orphan the live
    artifact sitting at `new` (review F1, round 3)."""
    project = doc.get("project")
    if not isinstance(project, str) or not project:
        raise ValueError("this proposal has no single source project")
    roots = open_store(root, StoreMode.READ).load_registry().get(project)
    if not roots:
        raise ValueError(f"proposal project {project!r} is not registered")
    return [Path(entry) for entry in roots]


def candidate_target_paths(root: Path, doc: store.Document) -> list[Path]:
    """Every place this proposal's managed artifact could plausibly be installed,
    most-authoritative first (ADR-0020 D39, review F1 round 3).

    Liveness must **fail closed across locations**: it is not enough to check the
    one path a fresh render would target. So this returns the recorded
    `installed_path` (the concrete file accept actually wrote — never ignored when
    non-null) *plus* the re-derived target under every registered project root
    (so a null `installed_path` still resolves, and a moved/re-registered project
    is still covered). Order-preserving and de-duplicated.

    Raises `ValueError` for an unknown proposal type or an unresolvable project —
    callers treat that as fail-closed, never as "gone"."""
    kind = str(doc.get("type") or "")
    slug = str(doc.get("name") or "")
    candidates: list[Path] = []

    recorded = doc.get("installed_path")
    if isinstance(recorded, str) and recorded:
        candidates.append(Path(recorded))

    if kind == "skill":
        scope = _skill_scope(doc)
        if scope == "user":
            candidates.append(Path.home() / ".claude" / "skills" / slug / "SKILL.md")
        else:
            for base in _project_roots(root, doc):
                candidates.append(base / ".claude" / "skills" / slug / "SKILL.md")
    elif kind == "rule":
        target = str(doc.get("target") or "")
        if target not in {"AGENTS.md", "CLAUDE.md"}:
            raise ValueError(f"invalid rule target {target!r}")
        for base in _project_roots(root, doc):
            candidates.append(base / target)
    else:
        raise ValueError(f"unsupported proposal type {kind!r}")

    seen: set[Path] = set()
    unique: list[Path] = []
    for path in candidates:
        if path not in seen:
            seen.add(path)
            unique.append(path)
    return unique


def candidate_is_live(text: str, doc: store.Document) -> bool:
    """Does this **existing** candidate target hold the proposal's managed
    artifact (ADR-0020 D39)? Callers only ask about candidates that exist.

    - **skill:** existence *is* liveness — a file at the canonical
      `<...>/skills/<slug>/SKILL.md` counts as live, full stop. We deliberately
      do **not** parse its frontmatter here. Ownership parsing is a text-format
      question, and every round of review found another representation
      (CRLF, CR-only, BOM, fence whitespace) that preserved the ownership values
      while defeating the parser — each one making a live skill look gone and
      orphanable. Existence has no such surface. The cost is that a skill the
      user *replaced* with their own content is non-revertable until they delete
      the file, which is the same "remove it by hand first" rule revert already
      documents, and errs toward never orphaning.
    - **rule:** the slug's `neurobase:rule:<slug>` marker is present, no matter
      what foreign bytes surround it — a plain substring search, immune to
      newline form and encoding markers. An edit *outside* the block leaves it
      live; deleting the block makes it gone (the file may well remain, holding
      the user's own content).
    """
    kind = str(doc.get("type") or "")
    slug = str(doc.get("name") or "")
    if kind == "skill":
        return True
    if kind == "rule":
        return _rule_start_marker(slug) in text
    return False


def _skill(root: Path, doc: store.Document, slug: str, draft: str, scope: str) -> Artifact:
    path = _skill_path(root, doc, slug, scope)
    before = _read_preserving(path)
    foreign = bool(before) and not _owned_skill(before, slug)
    # A draft that carries its own `---` frontmatter would otherwise be embedded
    # verbatim under our generated block — two frontmatter blocks, of which a
    # consumer reads only the first (G3). Strip it; salvage only its `description`,
    # the one field a draft author might legitimately set better than we can.
    draft_fm, body_src = _split_leading_frontmatter(draft)
    heading = next(
        (line[2:].strip() for line in body_src.splitlines() if line.startswith("# ")), None
    )
    body = body_src if heading is not None else f"# {slug}\n\n{body_src}"
    # `candidate_type` is a mining taxonomy label (`repeated-correction`), not a
    # description — prefer a human title: the draft's own `description`, else its
    # `#` heading; fall back to `candidate_type` only for a draft with neither (G3).
    draft_description = str(draft_fm.get("description") or "").strip() if draft_fm else ""
    fm: dict[str, Any] = {
        "name": slug,
        "description": draft_description or heading or str(doc.get("candidate_type") or slug),
        "neurobase_managed": True,
        "neurobase_slug": slug,
    }
    after = f"---\n{yaml.safe_dump(fm, sort_keys=False)}---\n\n{body.rstrip()}\n"
    return Artifact(path, before, after, f"{scope}-skill", foreign)


def _owned_skill(text: str, slug: str) -> bool:
    """Is ``text`` a SKILL.md Neurobase owns for ``slug`` — i.e. does its leading
    frontmatter carry both ownership keys (§12.8)?

    Parsed by **logical lines**, not by exact byte shapes. Ownership is a property
    of the frontmatter *values*; a value-preserving change to how the text is
    represented must not flip it. So a leading UTF-8 BOM is skipped, every
    standard newline form is accepted (``splitlines`` handles LF, CRLF and
    CR-only), and the ``---`` delimiter lines may carry surrounding whitespace.
    Matching `---\\n`/`\\r\\n` literally is exactly the mistake reviews F1 round 3
    (CRLF) and round 4 (CR-only, BOM, fence whitespace) each caught one instance
    of. Nothing is rewritten on disk — this normalizes for parsing only.

    NOTE this is no longer load-bearing for the revert/orphan invariant: skill
    liveness is decided by *existence* at the canonical path (``candidate_is_live``,
    ADR-0020 D39), precisely so no frontmatter-format edge case can make a live
    skill look gone. It still drives the accept flow's `foreign` warning and D40's
    never-claim-a-foreign-file exclusion, where a false negative is merely
    conservative."""
    lines = text.lstrip("﻿").splitlines()
    if not lines or lines[0].strip() != "---":
        return False
    for index in range(1, len(lines)):
        if lines[index].strip() == "---":
            try:
                fm = yaml.safe_load("\n".join(lines[1:index]))
            except yaml.YAMLError:
                return False
            return (
                isinstance(fm, dict)
                and fm.get("neurobase_managed") is True
                and fm.get("neurobase_slug") == slug
            )
    return False  # no closing fence — not frontmatter


def _rule(root: Path, doc: store.Document, slug: str, draft: str) -> Artifact:
    target = str(doc.get("target") or "")
    path = _rule_path(root, doc)
    before = _read_preserving(path)
    start = _rule_start_marker(slug)
    end = f"<!-- /neurobase:rule:{slug} -->"
    block = f"{start}\n{draft.rstrip()}\n{end}"
    start_count = before.count(start)
    end_count = before.count(end)
    s = before.find(start)
    e = before.find(end)
    # A target must hold exactly one correctly ordered start/end pair, or none.
    # Reversed markers (end before start) previously slipped the count check,
    # made the forward end-lookup miss, and appended a second block — corrupting
    # the file. Reject any duplicate, mismatched, or misordered pair up front.
    if start_count > 1 or end_count > 1 or (s >= 0) != (e >= 0) or (s >= 0 and e < s + len(start)):
        raise ValueError(f"target contains malformed or duplicate rule markers for {slug!r}")
    if s >= 0:
        after = before[:s] + block + before[e + len(end) :]
    else:
        heading = "## Neurobase-managed rules"
        addition = f"{heading}\n\n{block}\n" if heading not in before else f"{block}\n"
        separator = (
            ""
            if not before or before.endswith("\n\n")
            else ("\n" if before.endswith("\n") else "\n\n")
        )
        after = f"{before}{separator}{addition}"
    return Artifact(path, before, after, target)


def write_atomic(artifact: Artifact) -> None:
    artifact.path.parent.mkdir(parents=True, exist_ok=True)
    tmp = artifact.path.with_name(artifact.path.name + ".tmp")
    # newline="" disables translation so the spliced result — CRLF from the
    # preserved original, LF in our own block — is written byte-for-byte (§12).
    with open(tmp, "w", encoding="utf-8", newline="") as handle:
        handle.write(artifact.after)
    tmp.replace(artifact.path)
